using Game.Entities;
using Godot;
using System;

public partial class Keys : Area3D
{
    [Export]
    public string KeyId { get; set; } = "gold_key"; // map to level-specific id

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        // Generated by Copilot: Connect to the BodyEntered signal to detect when something enters the area
        BodyEntered += OnBodyEntered;
    }

    // Called every frame. 'delta' is the elapsed time since the previous frame.
    public override void _Process(double delta)
    {
    }

    //Generated by Copilot
    private void OnBodyEntered(Node body)
    {
        // Check if the entering body is the player (adjust "Player" if your node name differs)
        if (body is Farmer)
        {
            // Add the key to inventory (using its node name as ID)
            Game.Manager.Instance.Data.CollectedKeys.Add(KeyId);
            GD.Print($"Picked up key: {Name}");  // Debug log (remove in production)
            GD.Print($"Picked up key: {Game.Manager.Instance.Data.CollectedKeys[0]}");  // Debug log (remove in production)
            
            // Despawn the key
            QueueFree();
        }
    }
}
