using System;
using Game.Entities;
using Godot;

[GlobalClass]
public partial class Keys : Area3D
{
    [Export]
    public DoorInfo Info { get; set; } = new();

    [Export]
    AnimationPlayer player = null!;

    [Export]
    MeshInstance3D mesh = null!;

    [Export]
    StringName spinAnim = "spin";
    
    [Export]
    Item resource = null!;

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        ((StandardMaterial3D)mesh.Mesh.SurfaceGetMaterial(0)).AlbedoColor = Info.DoorColor;
        BodyEntered += OnBodyEntered;
        player.Play(spinAnim);
    }

    //Generated by Copilot
    private void OnBodyEntered(Node body)
    {
        if (body is Farmer)
        {
            // Add the key to inventory (using its ID)
            Game.Manager.Instance.Data.CollectedKeys.Add(Info.LockID);
            Game.Manager.Instance.inventory.AddItem(resource);
            GD.Print($"Picked up key: {Info.LockID}");
            //GD.Print($"Picked up key: {Game.Manager.Instance.Data.CollectedKeys}");

            // Despawn the key
            QueueFree();
        }
    }
}
