using System;
using Godot;
using MemoryPack;

namespace Game;

[MemoryPackable]
public partial class GameData
{
    // Add game-related save data here
    public int CurrentHealth { get; set; } = 100;

    // Generated by Copilot: track how many burgers the player has eaten
    public int BurgersEaten { get; set; } = 0;

    // TODO add health bar

    public ulong TimeGameStarted { get; set; }

    public GameData()
    {
        TimeGameStarted = Time.GetTicksMsec();
    }

    // public int FinalKilled { get; set; } = 0;

    // [MemoryPackIgnore]
    // public Action? FinalThingy { get; set; }
}
