using System;
using Godot;

namespace Game.Entities;

public partial class Pedestal : Area3D
{
    // Generated by Copilot: which statue belongs here
    [Export]
    public string RequiredStatueId { get; set; } = "statue1";

    private bool playerInZone = false;
    private bool placed = false;

    public override void _Ready()
    {
        BodyEntered += OnBodyEntered;
        BodyExited += OnBodyExited;

        // Generated by Copilot: initialize all 4 statue placement trackers
        var data = Game.Manager.Instance.Data;
        if (!data.StatuePlaced.ContainsKey("statue1"))
            data.StatuePlaced["statue1"] = false;
        if (!data.StatuePlaced.ContainsKey("statue2"))
            data.StatuePlaced["statue2"] = false;
        if (!data.StatuePlaced.ContainsKey("statue3"))
            data.StatuePlaced["statue3"] = false;
        if (!data.StatuePlaced.ContainsKey("statue4"))
            data.StatuePlaced["statue4"] = false;
    }

    private void OnBodyEntered(Node body)
    {
        if (body is Farmer)
        {
            playerInZone = true;
            if (!placed)
                GD.Print($"Pedestal ready for {RequiredStatueId}. Press [Accept] to place statue.");
        }
    }

    private void OnBodyExited(Node body)
    {
        if (body is Farmer)
            playerInZone = false;
    }

    public override void _PhysicsProcess(double delta)
    {
        if (!playerInZone || placed)
            return;

        if (!Input.IsActionJustPressed("ui_accept"))
            return;

        var data = Game.Manager.Instance.Data;
        if (string.IsNullOrEmpty(data.HeldStatueId))
        {
            GD.Print("You are not holding a statue to place.");
            return;
        }

        if (data.HeldStatueId != RequiredStatueId)
        {
            GD.Print($"This pedestal requires {RequiredStatueId}, but you are holding {data.HeldStatueId}.");
            return;
        }

        // Place statue successfully
        placed = true;
        data.HeldStatueId = null;
        data.StatuePlaced[RequiredStatueId] = true;

        GD.Print($"Placed statue '{RequiredStatueId}' on pedestal. ({RequiredStatueId} done.)");

        // Generated by Copilot: clear hand display when statue is placed
        var currentScene = GetTree().CurrentScene;
        Farmer? farmer = null;

        if (currentScene != null)
        {
            farmer = currentScene.FindChild("Farmer", true, false) as Farmer;
        }

        if (farmer == null)
        {
            var root = GetTree().Root;
            farmer = root.FindChild("Farmer", true, false) as Farmer;
        }

        if (farmer != null)
        {
            farmer.ClearHeldStatueDisplay();
        }

        // Generated by Copilot: check all statue doors to see if they should open
        if (currentScene != null)
        {
            // Generated by Copilot: recursively find all StatueDoor nodes
            var statueDoors = new System.Collections.Generic.List<StatueDoor>();
            CollectStatueDoors(currentScene, statueDoors);
            
            GD.Print($"[Pedestal] Found {statueDoors.Count} statue doors to check");
            foreach (var statueDoor in statueDoors)
            {
                GD.Print($"[Pedestal] Calling OpenIfStatuesPlaced on statue door");
                statueDoor.OpenIfStatuesPlaced();
            }
        }

        // Generated by Copilot: instantiate and display the statue that was placed
        var statueScene = GD.Load<PackedScene>("res://Scenes/Entities/Statue.tscn");
        if (statueScene != null)
        {
            var placedStatueInstance = statueScene.Instantiate<Statue>();
            placedStatueInstance.StatueId = RequiredStatueId;
            placedStatueInstance.SetPhysicsProcess(false); // Disable input processing for placed statue
            placedStatueInstance.SetProcess(false);
            AddChild(placedStatueInstance);
            placedStatueInstance.Position = new Vector3(0, 0.5f, 0); // Offset to show on pedestal
        }
    }

    // Generated by Copilot: helper method to recursively find all StatueDoor nodes in the scene tree
    private static void CollectStatueDoors(Node node, System.Collections.Generic.List<StatueDoor> doors)
    {
        if (node is StatueDoor statueDoor)
        {
            doors.Add(statueDoor);
        }

        foreach (Node child in node.GetChildren())
        {
            CollectStatueDoors(child, doors);
        }
    }
}
