using System;
using Godot;

namespace Game.Entities;

public partial class Pedestal : Area3D
{
    // Generated by Copilot: which statue belongs here
    [Export]
    public string RequiredStatueId { get; set; } = "statue1";

    private bool playerInZone = false;
    private bool placed = false;

    public override void _Ready()
    {
        BodyEntered += OnBodyEntered;
        BodyExited += OnBodyExited;
    }

    private void OnBodyEntered(Node body)
    {
        if (body is Farmer)
        {
            playerInZone = true;
            if (!placed)
                GD.Print($"Pedestal ready for {RequiredStatueId}. Press [Accept] to place statue.");
        }
    }

    private void OnBodyExited(Node body)
    {
        if (body is Farmer)
            playerInZone = false;
    }

    public override void _PhysicsProcess(double delta)
    {
        if (!playerInZone || placed)
            return;

        if (!Input.IsActionJustPressed("ui_accept"))
            return;

        var data = Game.Manager.Instance.Data;
        if (string.IsNullOrEmpty(data.HeldStatueId))
        {
            GD.Print("You are not holding a statue to place.");
            return;
        }

        if (data.HeldStatueId != RequiredStatueId)
        {
            GD.Print($"This pedestal requires {RequiredStatueId}, but you are holding {data.HeldStatueId}.");
            return;
        }

        // Place statue successfully
        placed = true;
        data.HeldStatueId = null;
        data.StatuePlaced[RequiredStatueId] = true;

        GD.Print($"Placed statue '{RequiredStatueId}' on pedestal. ({RequiredStatueId} done.)");

        // Generated by Copilot: instantiate and display the statue that was placed
        var statueScene = GD.Load<PackedScene>("res://Scenes/Entities/Statue.tscn");
        if (statueScene != null)
        {
            var placedStatueInstance = statueScene.Instantiate<Statue>();
            placedStatueInstance.StatueId = RequiredStatueId;
            placedStatueInstance.SetPhysicsProcess(false); // Disable input processing for placed statue
            placedStatueInstance.SetProcess(false);
            AddChild(placedStatueInstance);
            placedStatueInstance.Position = new Vector3(0, 0.5f, 0); // Offset to show on pedestal
        }
    }
}
