using System;
using Godot;

namespace Game.Entities;

public partial class Statue : Area3D
{
    // Generated by Copilot: unique statue identifier
    [Export]
    public string StatueId { get; set; } = "statue1";

    private bool playerInZone = false;

    public override void _Ready()
    {
        // Generated by Copilot: connect area signals
        BodyEntered += OnBodyEntered;
        BodyExited += OnBodyExited;
    }

    private void OnBodyEntered(Node body)
    {
        if (body is Farmer)
        {
            playerInZone = true;
            GD.Print($"Statue zone entered: {StatueId}. Press [Accept] to pick up.");
        }
    }

    private void OnBodyExited(Node body)
    {
        if (body is Farmer)
        {
            playerInZone = false;
        }
    }

    public override void _PhysicsProcess(double delta)
    {
        if (!playerInZone)
            return;

        if (!Input.IsActionJustPressed("ui_accept"))
            return;

        // Generated by Copilot: enforce one statue max carried
        var data = Game.Manager.Instance.Data;
        if (!string.IsNullOrEmpty(data.HeldStatueId))
        {
            GD.Print($"Already carrying statue '{data.HeldStatueId}'. Place it first.");
            return;
        }

        data.HeldStatueId = StatueId;
        GD.Print($"Picked up statue '{StatueId}'.");

        // Generated by Copilot: remove statue from world and disable collisions
        Visible = false;
        SetProcess(false);
        SetPhysicsProcess(false);

        var shape = GetNodeOrNull<CollisionShape3D>("CollisionShape3D");
        if (shape != null)
            shape.Disabled = true;

        // Optional: completely remove the object from the scene tree.
        // QueueFree();
    }
}
